language: python
cache: false

jobs:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39

before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools

install:
  - pip install tox

script:
  - tox

branches:
  only:
    - master
